HELP/base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home')
]

HELP/cursos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.lista_cursos, name='lista_cursos'),
    url(r'^pesquisa$', views.pesquisa_turma, name='pesquisa_turma'),
    url(r'^turma/(?P<pk>[0-9]+)/editar_turma$', views.editar_turma, name='editar_turma'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details_curso, name='details_curso'),
    url(r'^turma/(?P<pk>[0-9]+)/$', views.details_turma, name='details_turma'),
    url(r'^turma/(?P<pk>[0-9]+)/remover$', views.remover_turma, name='remover_turma'),
]

HELP/sistema/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)), # Url para pagina de admin
    url(r'^', include('base.urls', namespace='base', app_name = 'base')),
    url(r'^aluno/', include('aluno.urls', namespace='aluno', app_name = 'aluno')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios', app_name = 'usuarios')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos', app_name = 'cursos'))
]

HELP/cursos/models.py
# -*- coding: utf-8 -*-

################# MAKING THE NECESSARY IMPORTS ################

from __future__ import unicode_literals
from django.db import models
from django.conf  import settings
import datetime
from aluno.models import Aluno

################################################################


############### Modelo de Gerenciamento de Curso ###############

class Gerenciador_de_Curso(models.Manager):

	def search(self, query):
		return self.get_queryset().filter(
			models.Q(nome__icontains=query) | \
			models.Q(description__icontains=query)
			)

#################################################################



######################## Modelo de Curso ########################

class Curso(models.Model):

	nome = models.CharField('Nome', max_length=100)
	# O campo slug será utilizado como complemento da URL
	# Ex.: mysite.com/cursos/Nome_da_Slug
	slug = models.SlugField('Atalho')
	description = models.TextField('Descrição', blank=True)

	created_at = models.DateTimeField(
		'Criado em', auto_now_add=True
		)

	updated_at = models.DateTimeField(
		'Atualizado em', auto_now=True
		)

	objects = Gerenciador_de_Curso()

	def __str__(self):
		return self.nome

	class Meta:
		verbose_name = 'Curso'
		verbose_name_plural = 'Cursos'
		ordering = ['created_at']

#################################################################

class HorasFaltadas(models.Model):
	aluno = models.ForeignKey(Aluno)
	horas_faltadas = models.IntegerField(default=0)


######################## Modelo das Turmas ######################

class Turma(models.Model):

	curso = models.ForeignKey(Curso)
	codigo = models.CharField('Código', max_length=25, default='None', unique=True)
	professor = models.CharField('Professor', max_length=100)
	vagas_presencial = models.IntegerField('Vagas para lista presencial')
	vagas_lista_espera = models.IntegerField('Vagas para lista de espera')
	about = models.TextField('Informações Adicionais', blank=True)
	created_at = models.DateTimeField(
		'Criado em', auto_now_add=True
		)
	inicio = models.DateField("Data de Início", default=datetime.date.today)
	final = models.DateField("Data de Término", default=datetime.date.today)
	alunos_inscritos = models.ManyToManyField(Aluno, related_name='%(class)s_Aluno_inscrito')
	alunos_espera = models.ManyToManyField(Aluno, related_name='%(class)s_Aluno_espera')
	pauta = models.ManyToManyField(HorasFaltadas, related_name='%(class)s_Pauta')

	def __str__(self):
		return self.codigo

	class Meta:
		verbose_name = 'Turma'
		verbose_name_plural = 'Turmas'
		ordering = ['created_at']

#################################################################

HELP/cursos/forms.py
from django import forms
from .models import *

class Cadastro_Turma(forms.ModelForm):
	
	class Meta:
		model = Turma
		fields = ('codigo', 'professor', 'vagas_presencial', 'vagas_lista_espera',
			'about', 'inicio', 'final')

HELP/cursos/views.py
# -*- coding: utf-8 -*-

################# MAKING THE NECESSARY IMPORTS #################

from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from aluno.models import Aluno
import sys # Corrigir problema de acentuação
reload(sys) # Corrigir problema de acentuação
sys.setdefaultencoding('utf8') # Corrigir problema de acentuação


##################### View de Cursos #####################
### View para renderizar uma lista com todos os cursos cadastrados
@login_required
def lista_cursos(request):
	cursos = Curso.objects.all() # Pega todos os objetos
	context = {}
	context['cursos'] = cursos
	return render(request, 'lista_cursos.html', context)

##################### View de Pesquisa de turmas #####################
# View utilizada para pesquisar uma ou mais turmas
@login_required
def pesquisa_turma(request): 
    turmas = Turma.objects.order_by('codigo')
    context = {}
    query = request.GET.get("pesquisa")
    context['query'] = query
    if query:
        turmas = (turmas.filter(codigo__icontains=query)) or (turmas.filter(professor__icontains=query))
        context['turmas'] = turmas
    return render(request, 'pesquisa_turma.html', context)

############## View de detalhamento do Curso ##############
# View utilizada para detalhar o curso e utilizada para fazer
# o cadastro de uma turma 
@login_required
def details_curso(request, slug):
	cursos = get_object_or_404(Curso, slug=slug)
	context = {}
	context['cursos'] = cursos	

	if request.method == "POST":
		form = Cadastro_Turma(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.curso = Curso.objects.get(slug=slug)
			post.codigo = request.POST.get("codigo")
			post.professor = request.POST.get("professor")
			post.vagas_presencial = request.POST.get("vagas_presencial")
			post.vagas_lista_espera = request.POST.get("vagas_lista_espera")
			post.about = request.POST.get("about")
			post.inicio = request.POST.get("inicio")
			post.final = request.POST.get("final")
			post.save()
			return redirect('cursos:details_turma', pk=post.pk)
	else:
		form = Cadastro_Turma()

	context['form'] = form
	turmas = Turma.objects.filter(curso__slug=slug)
	context['turmas'] = turmas

	return render(request, 'details_curso.html', context)

############## View utilizada para editar uma turma ##############
# View que recupera uma turma do banco de dados de acordo com a "pk"
# e renderiza a turma para a edição 
@login_required
def editar_turma(request, pk):
	template_name = 'editar_turma.html'
	context = {}
	post = get_object_or_404(Turma, pk=pk)
	context['post'] = post
	if request.method == 'POST':
		form = Cadastro_Turma(request.POST, instance=post)
		if form.is_valid():
			form.save()
			form = Cadastro_Turma(instance=post)
			return redirect('cursos:details_turma', pk=post.pk)
	else:
		form = Cadastro_Turma(instance=post)

	context['form'] = form

	return render(request, template_name, context)

############## View para incrementar horas faltadas ##############
# View utilizada para incrementar as horas faltadas em uma turma para 
# todos os alunos da mesma
def incrementa_horas(turmas,horas):

	if horas:
		for it in turmas.pauta.all():
			it.horas_faltadas = it.horas_faltadas + int(horas.pop(0))
			it.save()

############## View para criar pauta ##############
# View utilizada para criar uma relação de um aluno com as horas
# faltadas pelo mesmo em uma turma
def cria_pauta(turma, aluno):
    pauta = HorasFaltadas()
    pauta.aluno = aluno
    pauta.horas_faltadas = 0
    pauta.save()
    turma.pauta.add(pauta)

############## View para remover um aluno de uma turma ##############
# View auxiliar utilizada para remover um ou mais alunos de uma turma
def remove_aluno(request, query, turmas):
	for a in query:
			aluno = Aluno.objects.get(pk=a)
			turmas.alunos_inscritos.remove(aluno)
			for it in turmas.pauta.all():
				if it.aluno == aluno:
					turmas.pauta.remove(it)
					messages.success(request,  aluno.nome +' foi removido da turma ' + turmas.curso.nome + '-' + turmas.codigo)

############## View para remover um aluno de uma lista de espera para uma turma ##############
# View auxiliar utilizada para remover um ou mais alunos da lista de espera
def remove_aluno_espera(request, mover, turmas):
	for b in mover:
			aluno = Aluno.objects.get(pk=b)
			turmas.alunos_espera.remove(aluno)
			messages.success(request,  aluno.nome +' foi removido da lista de espera da turma ' + turmas.curso.nome + '-' + turmas.codigo)

############## View para mover um aluno de uma lista de espera para uma turma ##############
# View auxiliar utilizada para mover um ou mais alunos da lista de espera
# para uma turma
def mover_aluno(request, mover, turmas):
	for b in mover:
			aluno = Aluno.objects.get(pk=b)

			if(turmas.alunos_inscritos.count() < turmas.vagas_presencial):
				turmas.alunos_espera.remove(aluno)
				turmas.alunos_inscritos.add(aluno)
				cria_pauta(turmas,aluno)
				messages.success(request,  aluno.nome +' foi movido para a turma ' + turmas.curso.nome + '-' + turmas.codigo)
			else:
				messages.warning(request, 'Turma ' + turmas.curso.nome + '-' + turmas.codigo + ' cheia, o aluno(a) ' + aluno.nome + ' permaneceu na lista de espera')


############## View para vizualizar os detalhes de uma turma ##############
# View utilizada para renderizar uma turma
# View utilizada para remover o aluno de uma turma
# View utilizada para mover um aluno da lista de espera para a turma
# View que atualiza a pauta
@login_required
def details_turma(request, pk):
	context = {}
	turmas = get_object_or_404(Turma, pk=pk)
	context['turmas'] = turmas
	alunos = turmas.alunos_inscritos.all()
	context['alunos'] = alunos
	espera = turmas.alunos_espera.all()
	context['espera'] = espera
	query = request.GET.getlist("a")
	horas = request.GET.getlist("h")
	mover = request.GET.getlist("e")
	botao_mover = request.GET.get("mover")
	botao_remover = request.GET.get("remover")
	incrementa_horas(turmas,horas)

	try:
		if query: # Se query for verdadeiro é pq tem aluno pra ser removido
			remove_aluno(request, query, turmas)
		if botao_mover: # Se botao_mover for verdadeiro é pq tem aluno pra ser movido		
			mover_aluno(request, mover, turmas)
		elif botao_remover: # Se bota_remover for verdadeiro é pq tem aluno pra ser removido da lista de espera
			remove_aluno_espera(request, mover, turmas)
			
	except Aluno.DoesNotExist:
		aluno = None
	return render(request, 'details_turma.html', context)


############### View de remocao de uma turma ##############
# View que remove uma turma de acordo com a "pk"
@login_required
def remover_turma(request, pk): # Funcao para remover uma turma
    turma = get_object_or_404(Turma, pk=pk)
    slug = turma.curso.slug
    turma.delete()
    return redirect('cursos:details_curso', slug=slug)

HELP/cursos/templates/details_curso.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div id="detalhesCurso">
    <!--Exibe o nome do curso -->
    <div id="infoCurso">
        <h1 class="cursoNome">{{ cursos }}</h1>

        <h3>Sobre o Curso</h3>
        <!--Exibe a descrição do curso -->
        <p class="descricaoCurso">{{ cursos.description }}</p>
    </div>    
    <!--Exibe as turmas cadastradas -->
    <h3>Lista de Turmas cadastradas</h3>

    {% for turma in turmas %}
    <tr>
        <td>Código:</td>
        <td>{{ turma }}</td>
        <td><a href="{% url 'cursos:details_turma' pk=turma.pk %}"><button type="submit"  class="botaoDetalhar">Detalhar</button></a></td><br>
    </tr><br>
    

    {% empty %}

    <p>Nenhuma turma cadastrada neste curso</p>

    {% endfor %}



    <!--Cadastrando uma nova turma -->
    <button type="submit" class="save btn btn-default" onclick="if(document.getElementById('cadastro').style.display=='none') {document.getElementById('cadastro').style.display=''}else{document.getElementById('cadastro').style.display='none'}">Cadastre uma nova Turma</button>

</div>

<div id="cadastro" style="display:none">

    <h2>Nova turma</h2>

    <form method="POST" class="post-form">
        {% csrf_token %}
        <label class="campos" for="codigo">Código:</label><br>
        <input type="text" name="codigo" id="codigo" required><br>
        <p></p>

        <label class="campos" for="professor">Professor(a):</label><br>
        <input type="text" name="professor" id="professor" required><br>
        <p></p>

        <table>
            <tr>
                <td>
                    <label class="campos" for="vagas_presencial">Vagas:</label>
                </td>
                <td>
                    <label class="campos" for="vagas_lista_espera">Vagas lista de espera:</label>
                </td>
            </tr>

            <td>
                <input type="number" name="vagas_presencial" id="vagas_presencial" required>  
            </td>
            <td >
                <input type="number" name="vagas_lista_espera" id="vagas_lista_espera" required>
            </td>
        </table><br>
        
        <label class="campos" for="about">Informações adicionais:</label><br>
        <input type="text" name="about" id="about" required><br>
        <p></p>

        <table>
            <tr>
                <td>
                    <label class="campos" for="inicio">Data de início:</label>
                </td>
                <td>
                    <label class="campos" for="final">Data de término:</label>
                </td>
            </tr>

            <td>
                <input class="sDate" type="date" name="inicio" id="inicio" required>  
            </td>
            <td >
                <input class="sDate" type="date" name="final" id="final" required>  
            </td>
        </table>
        <!--Botão de confirmação-->
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
</div>

{% endblock %}

HELP/cursos/templates/details_turma.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div id="turma">
    <h1 class="titulo">
      {{turmas.curso}} - {{ turmas }}
  </h1>
</div>

<div id="turma">
    <table >

        <colgroup>
        <col class="coluna1">
        <col class="coluna2">
    </colgroup>

    <caption>Perfil da turma</caption>
    <tr>
        <td class="itens">Curso:</td>
        <td> {{ turmas.curso }} </td>
    </tr>
    <tr>
        <td class="itens">Código:</td>
        <td>{{ turmas.codigo }}</td>
    </tr>
    <tr>
        <td class="itens">Professor:</td>
        <td>{{ turmas.professor }}</td>
    </tr>
    <tr>
        <td class="itens">Vagas(Presencial):</td>
        <td>{{ turmas.vagas_presencial }}</td>
    </tr>
    <tr>
        <td class="itens">Vagas(Lista de Espera):</td>
        <td>{{ turmas.vagas_lista_espera }}</td>
    </tr>
    <tr>
        <td class="itens">Data de Início:</td>
        <td>{{ turmas.inicio }}</td>
    </tr>
    <tr>
        <td class="itens">Previsão de Término:</td>
        <td>{{ turmas.final }}</td>
    </tr>
</table>
</div>

<p></p>

<a class="btn btn-default" href="{% url 'cursos:editar_turma' pk=turmas.pk %}"><span class="glyphicon glyphicon-pencil"></br>Editar</span></a> <!-- Botao para editar a turma -->

<a class="btn btn-default" href="{% url 'cursos:remover_turma' pk=turmas.pk %}" onclick="return confirm('Você tem certeza que quer deletar a turma {{turmas.curso}} - {{turmas.codigo}}?')"><span class="fa fa-trash"></br>Excluir</span> </a>  <!-- Botao para e remover a turma -->

<a class="btn btn-default" onclick="if(document.getElementById('turma_alunos').style.display=='none') {document.getElementById('turma_alunos').style.display=''; document.getElementById('pauta').style.display='none'; document.getElementById('espera').style.display='none'}else{document.getElementById('turma_alunos').style.display='none'}"><span class="glyphicon glyphicon-book"></br>Alunos</span></a>

<a class="btn btn-default" onclick="if(document.getElementById('pauta').style.display=='none') {document.getElementById('pauta').style.display=''; document.getElementById('turma_alunos').style.display='none'; document.getElementById('espera').style.display='none'}else{document.getElementById('pauta').style.display='none'}"><span class="fa fa-list"></br>Pauta</span></a>

<a class="btn btn-default" onclick="if(document.getElementById('espera').style.display=='none') {document.getElementById('espera').style.display=''; document.getElementById('turma_alunos').style.display='none'; document.getElementById('pauta').style.display='none'}else{document.getElementById('espera').style.display='none'}"><span class="fa fa-ban"></br>Espera</span></a>

<a  class="btn btn-default" href="{% url 'cursos:details_curso' slug=turmas.curso.slug %}"><span  class="glyphicon glyphicon-arrow-left"><br/>Voltar</span></a>

{% if messages %}
<div class="message">
</br>
{% for msg in messages %}
<div class="alert alert-{{msg.level_tag}}" role="alert">
    {{ msg }}
</div>
{% endfor %}
</div>
{% endif %}

<div id="turma_alunos" style="display:none">
    <form method="GET" class="post-form">
        {% if alunos %}
        <h2>Alunos inscritos no curso</h2>
        <table class="tabelaInscritos table table-bordered">
            {% for aluno in alunos %}
            <tr>
                <td class="col-lg-1 "><input type="checkbox" name="a" value= "{{ aluno.pk }}"></td>
                <td class="col-lg-8">{{ aluno.nome }}</td>  
                <td class="col-lg-3">{{aluno.numero_matricula}}</td>
            </tr>
            {% endfor %}
        </table>
        <button class="btn btn-primary" type="submit">Remover aluno</button>
        {% else %}
        <h4>Não há alunos inscritos na turma!</h4>
        {% endif %}   
    </form>
</div>

<div id="pauta" style="display:none"> 
    <form method="GET" class="post-form">
        {% if turmas.pauta.first %}
    </br>
    <table class="table table-hover table-bordered tabelaPauta">  
        <tr>
            <td class="col-lg-6 info tabelaFalta"><h3>Alunos</h3></td>
            <td class="col-lg-2 info tabelaFalta" ><h3>Horas</h3></td>
            <td class="col-lg-4 info tabelaFalta"><h3>Total de Faltas</h3></td>
        </tr>
        {% for pauta in turmas.pauta.all %}
        <tr>
            <td><h4>{{ pauta.aluno }}</h4></td>
            <td><input type="number" name="h" id="horas_faltadas" value= "0"></td>
            <td><h4 class="tabelaFalta">{{pauta.horas_faltadas}}</h4></td>
        </tr> 
        {% endfor %}
    </table>
    <button class="btn btn-primary" type="submit">Salvar</button>
    {% else %}
    <h4>Não há alunos inscritos na turma!</h4>
    {% endif %}
</form>
</div>

<div id="espera" style="display:none">
    <form method="GET" class="post-form">
        {% if espera %}
        <h2>Alunos na lista de espera</h2>
        <table class="tabelaInscritos table table-bordered">
            {% for aluno in espera %}
            <tr>
                <td class="col-lg-1"><input type="checkbox" name="e" value= "{{ aluno.pk }}"></td>
                <td class="col-lg-8">{{ aluno.nome }}</td>  
                <td class="col-lg-3">{{aluno.numero_matricula}}</td>
            </tr>
            {% endfor %}
        </table>
        <button class="btn btn-primary" type="submit" name="mover" value="1">Mover aluno</button>
        <button class="btn btn-primary" type="submit" name="remover" value="1">Remover aluno</button>
        {% else %}
        <h4>Não há alunos na lista de espera!</h4>
        {% endif %}   
    </form>
</div>

{% endblock %}

HELP/cursos/templates/editar_turma.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div id="cadastro">
    <h2>Edição da turma</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <label class="campos" for="codigo">Código:</label><br>
        <input type="text" name="codigo" id="codigo" value="{{post.codigo}}"><br>
        <p></p>

        <label class="campos" for="professor">Professor(a):</label><br>
        <input type="text" name="professor" id="professor" value="{{post.professor}}"><br>
        <p></p>

        <label class="campos" for="vagas_presencial">Vagas:</label><br>
        <input type="text" name="vagas_presencial" id="vagas_presencial" value="{{post.vagas_presencial}}"><br>
        <p></p>

        <label class="campos" for="vagas_lista_espera">Vagas lista de espera:</label><br>
        <input type="text" name="vagas_lista_espera" id="vagas_lista_espera" value="{{post.vagas_lista_espera}}"><br>
        <p></p>

        <label class="campos" for="about">Informações adicionais:</label><br>
        <input type="text" name="about" id="about" value="{{post.about}}"><br>
        <p></p>

        <table>
            <tr>
                <td>
                    <label class="campos" for="inicio">Data de início:</label>
                </td>
                <td>
                    <label class="campos" for="final">Data de término:</label>
                </td>
            </tr>

            <td>
                <input class="sDate" type="date" name="inicio" id="inicio" value="{{post.inicio.isoformat}}">  
            </td>
            <td >
                <input class="sDate" type="date" name="final" id="final" value="{{post.final.isoformat}}">  
            </td>
        </table>
        <!--Botão de confirmação-->
        <button type="submit" class="save btn btn-default">Salvar</button>
    </form>
    
</div>

{% endblock %}

HELP/cursos/templates/lista_cursos.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="listagemCurso">
	
	<h2>Listagem de Cursos do NCD</h4>
		
	</div>

	{% for course in cursos %}
	<div class="nomeCurso">

		<h3><a href="{% url 'cursos:details_curso' course.slug %}" title="">{{ course.nome }}</a></h4>
			
		</div>
		{% empty %}
		<div class="nomeCurso">
			
			<p>Nenhum curso está disponível na plataforma</p>

		</div>
		{% endfor %}
		{% endblock %}

HELP/cursos/templates/pesquisa_turma.html
{% extends 'base.html' %}
{% block content %}
<body>
	<div class="pesquisa-alunos"> <!-- caixa de pesquisa -->
		<form method="GET" action="">
			<input type="text" name="pesquisa" placeholder="Pesquisa por código ou professor..." value = '{{ request.get.pesquisa }}'/>
			<button class="botaoPesquisar" type="submit">Pesquisar</button>
		</form>
	</div>

	<div class="lista-alunos"> <!-- imprimir turmas presente na lista de turmas-->
		{% if query %}
		{% for turma in turmas %}	
		<a href="{% url 'cursos:details_turma' pk=turma.pk %}">{{ turma.codigo }}<br/></a>
		{% empty %}
		<p>{{query}} não foi encontrado(a) no sistema</p>
		{% endfor %}
		{% endif %}
	</div>
</body>
{% endblock %}