HELP/aluno/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^novo$', views.novo, name='novo'), # URL para criar um novo aluno
	url(r'^pesquisa$', views.pesquisa, name='pesquisa'), # URL para pesquisar os alunos
	url(r'^lista$', views.lista, name='lista'), # URL para exibir a lista de alunos salvos
	url(r'^post/(?P<pk>\d+)/edit/$', views.editar, name='editar'), # URL para editar um aluno
	url(r'^aluno/(?P<pk>[0-9]+)/$', views.detalhes, name='detalhes'), # URL para mostrar os detalhes de um aluno
	url(r'^aluno/(?P<pk>[0-9]+)/remover$', views.remover, name='remover'), # URL para remover um aluno
]

HELP/base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home')
]

HELP/cursos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.lista_cursos, name='lista_cursos'),
    url(r'^pesquisa$', views.pesquisa_turma, name='pesquisa_turma'),
    url(r'^turma/(?P<pk>[0-9]+)/editar_turma$', views.editar_turma, name='editar_turma'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details_curso, name='details_curso'),
    url(r'^turma/(?P<pk>[0-9]+)/$', views.details_turma, name='details_turma'),
    url(r'^turma/(?P<pk>[0-9]+)/remover$', views.remover_turma, name='remover_turma'),
]

HELP/sistema/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)), # Url para pagina de admin
    url(r'^', include('base.urls', namespace='base', app_name = 'base')),
    url(r'^aluno/', include('aluno.urls', namespace='aluno', app_name = 'aluno')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios', app_name = 'usuarios')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos', app_name = 'cursos'))
]

HELP/usuarios/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views

urlpatterns = [
    url(r'^$', views.login,
    {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', views.logout,
    {'next_page': 'base:home'}, name='logout'),
    url(r'^cadastre-se$', register, name='register'),
    url(r'^painel$', painel, name='painel'),
    url(r'^editar$', edit, name='edit'),
    url(r'^nova-senha$', edit_password, name='edit_password'),
    url(r'^recuperar_senha$', password_reset, name='password_reset'),
    url(r'^confirmar_nova_senha/(?P<key>\w+)$', password_reset_confirm, name='password_reset_confirm'),
]

HELP/base/models.py
from django.db import models

# Create your models here.

HELP/base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
	return render(request,'home.html')

HELP/base/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>NCD</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="{% static 'css/style4.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/detalhes.css' %}">
    

</head>

<body>
    <div class="wrapper">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>NCD HELP!</h3>
                <strong>HELP!</strong>
            </div>

            <ul class="list-unstyled components">

             <li>
                <a href="{% url 'base:home' %}">
                    <i class="glyphicon glyphicon-home"></i>
                    Home
                </a>
            </li>
            
            <li class="inactive">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
                    <i class="glyphicon glyphicon-user"></i>
                    Aluno
                </a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li><a href="{% url 'aluno:novo' %}">Novo</a></li>
                    <li><a href="{% url 'aluno:pesquisa' %}">Pesquisa</a></li>
                    <li><a href="{% url 'aluno:lista' %}">Lista</a></li>
                </ul>
            </li>

            <li>
                <a href="#cursoSubmenu" data-toggle="collapse" aria-expanded="false">
                    <i class="fa fa-edit"></i>
                    Curso
                </a>
                <ul class="collapse list-unstyled" id="cursoSubmenu">
                    <li><a href="{% url 'cursos:lista_cursos' %}">Lista</a></li>
                    <li><a href="{% url 'cursos:pesquisa_turma' %}">Pesquisar Turma</a></li>
                </ul>
            </li>

            <li>
                <a href="#listaSubmenu" data-toggle="collapse" aria-expanded="false">
                    <i class="fa fa-group"></i>
                    Lista de espera
                </a>
                <ul class="collapse list-unstyled" id="listaSubmenu">
                    <li><a href="#">Novo</a></li>
                    <li><a href="#">Remover</a></li>
                    <li><a href="#">Lista</a></li>
                </ul>
            </li>

            <li>
                <a href="#listaPonto" data-toggle="collapse" aria-expanded="false">
                    <i class="fa fa-hourglass-end"></i>
                    Ponto
                </a>
                <ul class="collapse list-unstyled" id="listaPonto">
                    <li><a href="#">Entrada</a></li>
                    <li><a href="#">Saída</a></li>
                    <li><a href="#">Banco de Horas</a></li>
                </ul>
            </li>

            <li>
                <a href="#">
                    <i class="glyphicon glyphicon-send"></i>
                    Contato
                </a>
            </li>
        </ul>

    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-default">
            <div class="container-fluid">

                <div class="navbar-header">
                    <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                        <i class="glyphicon glyphicon-align-left"></i>
                        <span>Menu</span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'usuarios:painel' %}">Painel</a></li>
                        <li><a href="{% url 'usuarios:logout' %}">Sair</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock %}
        
    </div>
</div>

<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<!-- Bootstrap Js CDN -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script type="text/javascript">
 $(document).ready(function () {
     $('#sidebarCollapse').on('click', function () {
         $('#sidebar').toggleClass('active');
     });
 });
</script>

<script>
    $(document).ready(function() {
        // messages timeout for 10 sec 
        setTimeout(function() {
            $('.message').fadeOut('slow');
                }, 5000); // <-- time in milliseconds, 1000 =  1 sec

        // delete message
        $('.alert alert-{{msg.level_tag}}').live('click',function(){
            $('.alert alert-{{msg.level_tag}}').parent().attr('style', 'display:none;');
        })
    });
</script>

</body>
</html>

HELP/base/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h2>Bem vindo ao NCD Help! Em breve novas ferramentas!</h2>
{% endblock %}