HELP/base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home')
]

HELP/sistema/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)), # Url para pagina de admin
    url(r'^', include('base.urls', namespace='base', app_name = 'base')),
    url(r'^aluno/', include('aluno.urls', namespace='aluno', app_name = 'aluno')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios', app_name = 'usuarios')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos', app_name = 'cursos'))
]

HELP/usuarios/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views

urlpatterns = [
    url(r'^$', views.login,
    {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', views.logout,
    {'next_page': 'base:home'}, name='logout'),
    url(r'^cadastre-se$', register, name='register'),
    url(r'^painel$', painel, name='painel'),
    url(r'^editar$', edit, name='edit'),
    url(r'^nova-senha$', edit_password, name='edit_password'),
    url(r'^recuperar_senha$', password_reset, name='password_reset'),
    url(r'^confirmar_nova_senha/(?P<key>\w+)$', password_reset_confirm, name='password_reset_confirm'),
]

HELP/usuarios/models.py
# -*- coding: utf-8 -*-

######################## MAKING THE NECESSARY IMPORTS ############################

from __future__ import unicode_literals
import re
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
from django.conf import settings

##################################################################################


############### Model de Equipe #######################################

############################################################################


################################# Model de Usuário #####################################

class User(AbstractBaseUser, PermissionsMixin):

	username = models.CharField(
		'Nome de Usuário', max_length=30, unique=True,
		validators = [validators.RegexValidator(re.compile('^[\w.@+-]+$'),
			'Apenas são permitidos letras, números ou os caracteres: @ . + - _', 'invalid')]
		)
	email = models.EmailField('E-mail', help_text='Digite seu email criado pelo NCD', unique=True)
	name = models.CharField('Nome', max_length=100, blank=True)
	#equipe = models.CharField(max_length=100, choices=Equipe.choices)
	is_active = models.BooleanField('Está Ativo?', blank=True, default=True)
	is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
	date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

	objects = UserManager()

	USERNAME_FIELD = 'username' #Campo que é utilizado para logar
	REQUIRED_FIELDS = ['email'] #Campo chave para superusuário

	#Representação string do usuário
	def __str__(self):
		return self.name or self.username

	def get_short_name(self):
		return self.username

	def get_full_name(self):
		return str(self)

	class Meta:
		verbose_name = 'Usuário'
		verbose_name_plural = 'Usuários'

##################################################################################


######################### Model Para Recuperação de senha ########################

class PasswordReset(models.Model):

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL, verbose_name='Usuário',
		related_name='resets'
		)
	key = models.CharField('Chave', max_length=100, unique=True)
	created_at = models.DateTimeField('Criado em', auto_now_add=True)
	confirmed = models.BooleanField('Confirmado', default=False, blank=True)

	def __str__(self):
		return '{0} em {1}'.format(self.user, self.created_at)

	class Meta:
		verbose_name = 'Nova Senha'
		verbose_name_plural = 'Novas Senhas'
		ordering = ['-created_at']

###################################################################################

HELP/usuarios/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from base.utils import generate_hash_key
from base.mail import send_mail_template
from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):
	email = forms.EmailField(label='Email')

	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			return email
		raise forms.ValidationError(
			'Nenhum usuário encontrado com este Email'
		)

	def save(self):
		user = User.objects.get(email=self.cleaned_data['email'])
		key = generate_hash_key(user.username)
		reset = PasswordReset(key=key, user=user)
		reset.save()
		template_name = 'password_reset_mail.html'
		subject = 'Criar nova senha no NCD Help!'
		context = {
			'reset': reset,
		}
		send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(forms.ModelForm):
	email = forms.EmailField(label="E-mail")
	password1 = forms.CharField(label='Senha', widget = forms.PasswordInput)
	password2 = forms.CharField(
		label='Confirmação de Senha', widget = forms.PasswordInput)


	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError('As Senhas não Coincidem!')
		return password2

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user

	class Meta:
		model = User
		fields = ['name', 'username', 'email']

class EditAccountForm(forms.ModelForm):

	def clean_email(self):
		email = self.cleaned_data['email']
		queryset = User.objects.filter(
			email=email).exclude(pk=self.instance.pk)
		if queryset.exists():
			raise forms.ValidationError('Ja existe um usuário com este E-mail')
		return email

	class Meta:
		model = User
		fields = ['name', 'username', 'email']

HELP/usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, get_user_model
from django.conf import settings
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import PasswordReset
from base.utils import generate_hash_key
from django.contrib import messages

User = get_user_model()

####################### PAINEL DO USUÁRIO ####################### 
@login_required
def painel(request):
	template_name = 'painel.html'
	context = {}
	return render(request, template_name, context)



################## PAINEL DO USUÁRIO - EDIÇÃO ##################
@login_required
def edit(request):
	template_name = 'edit.html'
	context = {}
	post = request.user
	context['post'] = post
	if request.method == 'POST':
		form = EditAccountForm(request.POST, instance=request.user)
		if form.is_valid:
			form.save()
			form = EditAccountForm(instance=request.user)
			context['sucess'] = True
			return redirect('usuarios:painel')

	else:
		form = EditAccountForm(instance=request.user)

	context['form'] = form
	return render(request, template_name, context)

###################### PÁGINA DE EDIÇÃO DE SENHA ######################
@login_required
def edit_password(request):
	template_name = 'edit_password.html'
	context = {}
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			context['success'] = True
	else:
		form = PasswordChangeForm(user=request.user)

	context['form'] = form
	return render(request, template_name, context)

##################### REGISTRO DE USUÁRIO #####################
def register(request):
	template_name = 'cadastro.html'
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			user = authenticate(
				username=user.username, password=form.cleaned_data['password1']
				)
			login(request, user)

			return redirect('base:home')
	else:
		form = RegisterForm()

	context = {
		'form': form
	}
	return render(request, template_name, context)

################## PÁGINA DE ALTERAÇÃO DE SENHA ##################
def password_reset(request):
	template_name = 'password_reset.html'
	context = {}
	form = PasswordResetForm(request.POST or None)
	if form.is_valid():
		form.save()
		context['success'] = True
	context['form'] = form
	return render(request, template_name, context)

############# PÁGINA DE SOLICITAÇÃO DE ALTERAÇÃO DE SENHA #############
def password_reset_confirm(request, key):
	template_name = 'password_reset_confirm.html'
	context = {}
	reset = get_object_or_404(PasswordReset, key=key)
	form = SetPasswordForm(user=reset.user, data=request.POST or None)
	if form.is_valid():
		form.save()
		context['success'] = True
	context['form'] = form
	return render(request, template_name, context)

HELP/usuarios/templates/cadastro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>NCD HELP!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->  
    <link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->  
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
    <!--===============================================================================================-->

</head>
<body>
    
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="{% static 'login/images/Logo.png' %}" alt="IMG">
                </div>

                <form class="login100-form validate-form" action = "{% url 'usuarios:register' %}" method="post">
                    {% csrf_token %}
                    <span class="login100-form-title">
                        Novo usuário
                    </span>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="name" id = "name" placeholder="Digite seu Nome">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-address-book" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="email" name="email" id = "email" placeholder="Email">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="username" id = "username" placeholder="Nome de usuário">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-users" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input type="password" name="password1" class="input100" placeholder="Senha">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input type="password" name="password2" class="input100" placeholder="Confirme sua senha">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Criar conta
                        </button>
                    </div>

                    <div class="text-center p-t-80">
                        <a class="txt2" href="{% url 'usuarios:login' %}">
                            <i class="fa fa-long-arrow-left m-l-5" aria-hidden="true"></i>
                            Voltar 
                        </a>
                    </div>
                </form>

            </div>
        </div>
    </div>
    
    <!--===============================================================================================-->  
    <script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script >
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

HELP/usuarios/templates/edit.html
{% extends "painel.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="item"><a href="{% url 'usuarios:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}

<form class="editar_user" action = "{% url 'usuarios:edit' %}" method="post">
    {% csrf_token %}

    <div>
        <span class="span">Nome:</span></br> <input class="input100" type="text" name="name" id = "name" value="{{user.name}}">
    </div>

    <div class="wrap-input100 validate-input">
        <span class="span">Username:</span></br> <input class="input100" type="text" name="username" id = "username" required value="{{user.username}}">
    </div>

    <div class="wrap-input100 validate-input">
        <span class="span">Email:</span></br> <input class="input100" type="email" name="email" id = "email" required value="{{post.email}}">
    </div>

    <div class="container-login100-form-btn">
        <button class="login100-form-btn" type="submit">
            Salvar Modificações
        </button>
    </div>
</form>
{% endblock %}

HELP/usuarios/templates/edit_password.html
{% extends "painel.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="item"><a href="{% url 'usuarios:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}

<form class="editar_user" action = "{% url 'usuarios:edit_password' %}" method="post">
    {% csrf_token %}

    <div class="wrap-input100 validate-input">
        <span class="span">Senha antiga:</span></br> <input class="input100" type="password" name="old_password" id = "old_password">
    </div>

    <div class="wrap-input100 validate-input">
        <span class="span">Nova Senha:</span></br> <input class="input100" type="password" name="new_password1" id = "new_password1">
    </div>

    <div class="wrap-input100 validate-input">
        <span class="span">Confirmação da nova senha:</span></br> <input class="input100" type="password" name="new_password2" id = "new_password2">
    </div>

    <div class="container-login100-form-btn">
        <button class="login100-form-btn" type="submit">
            Alterar Senha
        </button>
    </div>
</form>

{% if success %}
<br/><span class="aviso-alteracao-senha">Sua senha foi alterada com sucesso!</span>
{% endif %}

{% endblock %}

HELP/usuarios/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>NCD HELP!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->  
    <link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->  
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
    <!--===============================================================================================-->

</head>
<body>
    
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="{% static 'login/images/Logo.png' %}" alt="IMG">
                </div>

                <form class="login100-form validate-form" action = "" method="post">
                    {% csrf_token %}
                    <span class="login100-form-title">
                        Bem vindo
                    </span>

                    <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                        <input class="input100" type="text" name="username" placeholder="Login">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input type="password" name="password" class="input100" placeholder="Senha">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                    <div class="text-center p-t-12">
                        
                       <a class="txt2" href="{% url 'usuarios:password_reset' %}" title="Nova_senha">Esqueceu a Senha?</a> <br />
                       
                   </div>

                   <div class="text-center p-t-136">
                    <span class="login100-form-title">
                        Novo por Aqui?
                    </span>
                    <a class="txt2" href="{% url 'usuarios:register' %}">
                        Criar conta
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>




<!--===============================================================================================-->  
<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login/vendor/tilt/tilt.jquery.min.js' %}"></script>
<script >
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>
<!--===============================================================================================-->
<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

HELP/usuarios/templates/painel.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="menu-painel">
    <ul>
        <li class="item"><a href="{% url 'usuarios:painel' %}">Minha Conta</a></li>
        <li class="item"><a href="{% url 'usuarios:edit' %}">Editar Conta</a></li>
        <li class="item"><a href="{% url 'usuarios:edit_password' %}">Editar Senha</a></li>
    </ul>
</div>

<div id="breadcrumb">
    <ul class="breadcrumb">
        {% block breadcrumb %}
        <li class="item"><a href="{% url 'usuarios:painel' %}">Meu Painel</a></li>
        {% endblock %}
    </ul>
</div>

<div id="dados">
    {% block dashboard_content %}
    {% if user.name%}<p class="item"><strong>Nome</strong>: {{ user.name }}</p>{% endif %}
    <p class="item"><strong>Usuário</strong>: {{ user }}</p>
    <p class="item"><strong>E-mail</strong>: {{ user.email }}</p>
    {% endblock %}
</div>

{% endblock %}

HELP/usuarios/templates/password_reset.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>NCD HELP!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->  
    <link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->  
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
    <!--===============================================================================================-->

</head>
<body>
    
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="{% static 'login/images/Logo.png' %}" alt="IMG">
                </div>

                {% if success %}
                
                <div id="confirma-senha">
                    <h6>Um email foi enviado para você com mais detalhes da sua recuperação de senha</h6>
                </div>

                <div class="text-center p-t-80">
                    <a class="txt2" href="{% url 'usuarios:login' %}">
                        <i class="fa fa-long-arrow-left m-l-5" aria-hidden="true"></i>
                        Voltar 
                    </a>
                </div>

                {% else %}
                <form class="login100-form validate-form" action ="{% url 'usuarios:password_reset' %}" method="post">
                    {% csrf_token %}
                    <span class="login100-form-title">
                        Recuperação de Senha
                    </span>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="email" name="email" id = "email" placeholder="Digitar Email cadastrado">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Recuperar Senha
                        </button>
                    </div>

                    <div class="text-center p-t-80">
                        <a class="txt2" href="{% url 'usuarios:login' %}">
                            <i class="fa fa-long-arrow-left m-l-5" aria-hidden="true"></i>
                            Voltar 
                        </a>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    
    <!--===============================================================================================-->  
    <script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'login/vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script >
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'login/js/main.js' %}"></script>

HELP/usuarios/templates/password_reset_mail.html
<p>Olá Usuário do NCD Help!</p>
<p>Para criar uma nova senha, acesse o link: <a href="http://127.0.0.1:8000{% url 'usuarios:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">Criar Nova Senha</a></br></p>
<p>Dessa vez tente anotar sua senha para não esquecê-la.</p>
<p></br></p>
<p></br>Atenciosamente, equipe de TI do NCD.</p>