HELP/aluno/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^novo$', views.novo, name='novo'), # URL para criar um novo aluno
	url(r'^pesquisa$', views.pesquisa, name='pesquisa'), # URL para pesquisar os alunos
	url(r'^lista$', views.lista, name='lista'), # URL para exibir a lista de alunos salvos
	url(r'^post/(?P<pk>\d+)/edit/$', views.editar, name='editar'), # URL para editar um aluno
	url(r'^aluno/(?P<pk>[0-9]+)/$', views.detalhes, name='detalhes'), # URL para mostrar os detalhes de um aluno
	url(r'^aluno/(?P<pk>[0-9]+)/remover$', views.remover, name='remover'), # URL para remover um aluno
]

HELP/base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home')
]

HELP/cursos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.lista_cursos, name='lista_cursos'),
    url(r'^pesquisa$', views.pesquisa_turma, name='pesquisa_turma'),
    url(r'^turma/(?P<pk>[0-9]+)/editar_turma$', views.editar_turma, name='editar_turma'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details_curso, name='details_curso'),
    url(r'^turma/(?P<pk>[0-9]+)/$', views.details_turma, name='details_turma'),
    url(r'^turma/(?P<pk>[0-9]+)/remover$', views.remover_turma, name='remover_turma'),
]

HELP/sistema/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)), # Url para pagina de admin
    url(r'^', include('base.urls', namespace='base', app_name = 'base')),
    url(r'^aluno/', include('aluno.urls', namespace='aluno', app_name = 'aluno')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios', app_name = 'usuarios')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos', app_name = 'cursos'))
]

HELP/aluno/models.py
from django.db import models
from django.utils import timezone

class Aluno(models.Model):
	nome = models.CharField(max_length=100)
	nascimento = models.DateField()
	cpf = models.CharField(max_length=11, unique = True)
	genero = models.CharField(max_length=20, default = '')
	telefone = models.CharField(max_length=12, blank = True)
	celular = models.CharField(max_length=12, default = '', blank = True)
	email = models.EmailField(max_length=100, default = '', blank = True)
	data_entrada = models.DateTimeField(default=timezone.now)
	rua = models.CharField(max_length=100, default = '')	
	bairro = models.CharField(max_length=100, default = '')
	cidade = models.CharField(max_length=100, default = '')
	estado = models.CharField(max_length=100, default = '')
	complemento = models.CharField(max_length=100, default = '', blank = True)
	numero_matricula = models.CharField(max_length=20, unique = True, default='')
	nivelamento = models.CharField(max_length=100, default='')

	def publish(self):
		self.data_entrada = timezone.now()
		self.save()

	def __str__(self):
		return self.nome

HELP/aluno/forms.py
from django import forms
from .models import Aluno
from cursos.models import *

class PostForm(forms.ModelForm):

    class Meta:
        model = Aluno
        fields = ('nome', 'nascimento', 'cpf', 'genero', 'telefone', 'celular', 'email', 'rua', 'bairro', 'cidade', 'estado', 'complemento', 'nivelamento')
    
        
class newUserRegistration(forms.Form):
	nome = forms.CharField(widget=forms.TextInput(attrs={'type': 'text', 'id':'register-form-name', 'name':'register-form-name', 'value':"", 'class':'form-control'}))

class Escolha1(forms.ModelForm):

    class Meta:
        model = Curso
        fields = ('nome',)

class Escolha2(forms.ModelForm):

    class Meta:
        model = Turma
        fields = ('codigo',)

HELP/aluno/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Aluno
from cursos.models import Turma, Curso, HorasFaltadas
from .forms import PostForm
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages

##################### View de pesquisa de alunos #####################
# View que renderiza a lista de alunos dado uma pesquisa por nome, cpf ou numero de matricula
@login_required
def pesquisa(request): 
    alunos = Aluno.objects.order_by('nome')
    context = {}
    query = request.GET.get("pesquisa")
    context['query'] = query
    if query:
        alunos = (alunos.filter(nome__icontains=query)) or (alunos.filter(cpf__icontains=query)) or (alunos.filter(numero_matricula__icontains=query))
        context['alunos'] = alunos
    return render(request, 'pesquisa.html', context)

##################### View de lista de alunos #####################
# View que retorna uma lista de alunos ordenados por ordem alfabetica
@login_required
def lista(request):
    alunos = Aluno.objects.order_by('nome')
    return render(request, 'lista.html', {'alunos':alunos})

############## View para criar pauta ##############
# View utilizada para criar uma relação de um aluno com as horas
# faltadas pelo mesmo em uma turma
def cria_pauta(turma, aluno):
    pauta = HorasFaltadas()
    pauta.aluno = aluno
    pauta.horas_faltadas = 0
    pauta.save()
    turma.pauta.add(pauta)

##################### View para matricula de um aluno numa turma #####################
# View que matricula um aluno numa turma ou insere o aluno numa lista de espera
def matricula_aluno(request, query, aluno):
    for t in query:
        turma = Turma.objects.get(codigo=t)
        if(turma.alunos_inscritos.filter(pk = aluno.pk).count() > 0):
            messages.warning(request,  aluno.nome +' ja esta inscrito na turma ' + turma.curso.nome + '-' + turma.codigo, extra_tags='alert')
        elif(turma.alunos_inscritos.count() < turma.vagas_presencial):
            turma.alunos_espera.remove(aluno)
            turma.alunos_inscritos.add(aluno)
            cria_pauta(turma,aluno)
            messages.success(request,  aluno.nome +' foi inscrito(a) na turma ' + turma.curso.nome + '-' + turma.codigo)
        else:
            if (turma.alunos_espera.count() < turma.vagas_lista_espera):
                turma.alunos_espera.add(aluno)
                messages.info(request, 'Turma cheia, ' + aluno.nome + ' foi inscrito(a) na lista de suplencia da turma ' + turma.curso.nome + '-' + turma.codigo)
            else:
                messages.warning(request, 'Turma, e lista de suplencia cheias, ' + aluno.nome + ' nao foi inscrito(a) na turma ' + turma.curso.nome + '-' + turma.codigo)

##################### View de detalhamento de um aluno #####################
# View que renderiza um aluno de acordo com a "pk"
# View que permite inserir um aluno numa turma ou lista de espera
@login_required
def detalhes(request, pk):
    context = {}
    aluno = get_object_or_404(Aluno, pk=pk)
    turmas = Turma.objects.all()
    context['aluno'] = aluno
    context['turmas'] = turmas
    query = request.GET.getlist("turma")
    try:
        if query: # Se query for verdadeiro o aluno será inserido em uma ou mais turmas
            matricula_aluno(request, query, aluno)
    except Turma.DoesNotExist:
        turma = None
    return render(request, 'detalhes.html', context)

##################### View novo aluno #####################
# View utilizada para cadastrar um novo aluno no banco de dados
@login_required
def novo(request): 
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            now = datetime.now();
            post = form.save(commit=False)
            post.data_entrada = timezone.now()
            post.numero_matricula = datetime.now().strftime("%Y%m%d") + post.cpf[8:11];
            post.save()
            return redirect('aluno:detalhes', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'novo_editar.html', {'form': form})

##################### View de edicao de um aluno #####################
# View que recupera um aluno do banco de dados acordo com a "pk" e
# renderiza para edicao
@login_required
def editar(request, pk): # Funcao para editar um aluno
    post = get_object_or_404(Aluno, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('aluno:detalhes', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'novo_editar.html', {'form': form, 'post': post})

##################### View de remocao de um aluno #####################
# View que remove um aluno de acordo com a "pk"
@login_required
def remover(request, pk): # Funcao para remover um aluno
    context = {}
    aluno = get_object_or_404(Aluno, pk=pk)
    nome = aluno.nome
    context['nome']= nome
    aluno.delete()
    return render(request,'confirmacao.html', context)

HELP/aluno/templates/confirmacao.html
{% extends 'base.html'%}

{% block content %}
<body>
	<p>{{nome}} removido(a) com sucesso</p>
	</	body>
	{% endblock %}

HELP/aluno/templates/detalhes.html
{% extends 'base.html' %}
{% block content %}
<body>
   <div id="aluno">
    <table >

        <colgroup>
        <col class="coluna1">
        <col class="coluna2">
    </colgroup>

    <caption>Perfil do aluno</caption>
    <tr>
        <td class="itens">Nome:</td>
        <td> {{ aluno.nome }} </td>
    </tr>
    <tr>
        <td class="itens">CPF:</td>
        <td>{{ aluno.cpf }}</td>
    </tr>
    <tr>
        <td class="itens">Sexo:</td>
        <td>{{ aluno.genero }}</td>
    </tr>
    <tr>
        <td class="itens">Data de Nascimento:</td>
        <td>{{ aluno.nascimento }}</td>
    </tr>
    <tr>
        <td class="itens">Telefone:</td>
        <td>{{ aluno.telefone }}</td>
    </tr>
    <tr>
        <td class="itens">Celular:</td>
        <td>{{ aluno.celular }}</td>
    </tr>
    <tr>
        <td class="itens">E-Mail:</td>
        <td>{{ aluno.email }}</td>
    </tr>

    <tr>
        <td class="itens">Rua:</td>
        <td>{{ aluno.rua }}</td>
    </tr>
    <tr>
        <td class="itens">Bairro:</td>
        <td>{{ aluno.bairro }}</td>
    </tr>
    <tr>
        <td class="itens">Cidade:</td>
        <td>{{ aluno.cidade }}</td>
    </tr>
    <tr>
        <td class="itens">Estado:</td>
        <td>{{ aluno.estado }}</td>
    </tr>
    <tr>
        <td class="itens">Complemento:</td>
        <td>{{ aluno.complemento }}</td>
    </tr>
    <tr>
        <td class="itens">Nivelamento:</td>
        <td>{{ aluno.nivelamento }}</td>
    </tr>
    <tr>
        <td class="itens">Numero de Matricula:</td>
        <td>{{ aluno.numero_matricula }}</td>
    </tr>
</table>
<p></p>

<a class="btn btn-default" href="{% url 'aluno:editar' pk=aluno.pk %}"><span class="glyphicon glyphicon-pencil"></br>Editar</span></a> <!-- Botao para editar o aluno -->

<a class="btn btn-default" href="{% url 'aluno:remover' pk=aluno.pk %}" onclick="return confirm('Você tem certeza que quer deletar o(a) aluno(a) {{aluno.nome}}?')"><span class="fa fa-trash"></br>Excluir</span> </a>  <!-- Botao para e remover o aluno -->

<a class="btn btn-default" onclick="if(document.getElementById('cursos_aluno').style.display=='none') {document.getElementById('cursos_aluno').style.display=''; document.getElementById('inscricao').style.display='none'}else{document.getElementById('cursos_aluno').style.display='none'}"><span class="glyphicon glyphicon-book"></br>Turmas</span></a>

<a class="btn btn-default" onclick="if(document.getElementById('inscricao').style.display=='none') {document.getElementById('inscricao').style.display=''; document.getElementById('cursos_aluno').style.display='none'}else{document.getElementById('inscricao').style.display='none'}"><span class="glyphicon glyphicon-user"></br>Inscrição</span></a>

<a  class="btn btn-default" href="{% url 'aluno:lista' %}"><span  class="glyphicon glyphicon-arrow-left"><br/>Voltar</span></a>

{% if messages %}
<div class="message">
</br>
{% for msg in messages %}
<div class="alert alert-{{msg.level_tag}}" role="alert">
    {{ msg }}
</div>
{% endfor %}
</div>
{% endif %}

<div class="pure-menu pure-menu-open" style="display:none" id="cursos_aluno">
    <h2>Turmas em que o aluno está inscrito</h2>
    <ul>
     {% for turma in turmas %}
     {% for alunos in turma.alunos_inscritos.all %}
     {% if alunos.numero_matricula == aluno.numero_matricula %}
     <a href="{% url 'cursos:details_turma' pk=turma.pk %}"><h4>{{turma.curso}} - {{turma.codigo}}</h4></a>
 </br>
 {% endif %}
 {% endfor %}
 {% endfor %}
</ul>
</div>

<div id="inscricao" style="display:none">

    {% if turmas %}

    <h2>Turmas Disponíveis para inscrição</h2>
    <form method="GET" class="post-form">
        
        {% for turma in turmas %}
        <table class="inscricaoAluno">
            <tr>
                <td class="inscricaoAluno"><input type="checkbox" name="turma" value= "{{ turma.codigo }}"></td>
                <td class="inscricaoAluno">{{ turma.curso.nome }} - {{turma.codigo}}</td> 
            </tr>
        </table><br>
        <p></p><br>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Inscrever</button>
    </form>

    {% else %}
    <h4>Não há turmas cadastradas no sistema!</h4>
    {% endif %}
</div>   
</div>
</body>
{% endblock %}

HELP/aluno/templates/lista.html
{% extends 'base.html' %}
{% block content %}
<body>
	<div class="lista-alunos"> <!-- imprimir alunos presente na lista alunos-->
		<h2>Lista de Alunos:</h2>
		{% if alunos is null %}
		<p>não foi encontrado alunos no sistema</p>
		{% else %}
		<div id="listaAlunos">
			{% for aluno in alunos %}
			<table>
				<tr>
					<td class="nomeAlunos">
						<a href="{% url 'aluno:detalhes' pk=aluno.pk %}"> {{ aluno.nome }}</a>
					</td>
				</tr>
			</table>    
			{% endfor %}
		</div>
		{% endif %}
	</div>
</body>
{% endblock %}

HELP/aluno/templates/novo_editar.html
{% extends 'base.html' %}
{% block content %}
<body>

    <div class="editar">
        <!--Coloca o titulo para caso seja Novo Aluno ou para Editar Aluno-->
        {% if post.nome is null %}
        <h2>Novo Aluno</h2>
        {% else %}
        <h2>Editar Aluno</h2>
        {% endif %}

        <form method="POST" class="post-form">
            {% csrf_token %}
            <!--Entrada do nome do aluno-->
            <label class="campos sNome" for="nome">Nome:</label><br>
            <input type="text" name="nome" id="nome" required autofocus value="{{post.nome}}">
            <p></p>

            <!--Entrada de cpf do aluno-->
            <label class="campos" for="cpf">CPF:</label><br>
            <input type="text" name="cpf" id="cpf" maxlength="11" placeholder="Ex.:10881615800" required value="{{post.cpf}}"><br>

            <!--Tabela de entrada de Nascimento e Sexo-->
            <table>
                <tr>
                    <td>
                        <label class="campos" for="gender">Sexo:</label>   
                    </td>
                    <td >
                        <label class="campos " for="nascimento">Nascimento:</label>
                    </td>
                </tr><br>
                <tr>
                    <td>
                        <input class="sGender" type="text" list="genero" name="genero" id="genero"  maxlength="100" required autocomplete="off" value="{{post.genero}}">       
                    </td>

                    <td >
                        <input class="sDate" type="date" name="nascimento" id="nascimento" required value="{{post.nascimento.isoformat}}">
                        

                    </td>
                    <datalist id="genero">
                        <option value="Masculino">masculino</option>
                        <option value="Feminino">feminino</option>
                    </datalist>
                </tr>

            </table>    
            <p></p>

            <!--Entrada de telefone e celular-->
            <table> 
                <tr>                    
                    <td>
                        <label class="campos" for="telefone">Telefone:</label>
                    </td>
                    <td>
                        <label class="campos" for="celular">Celular:</label>
                    </td>   
                </tr>    
                <tr>
                    <td>
                        <input class="sTelefone" type="tel" name="telefone" id="telefone" maxlength="11" value="{{post.telefone}}">
                    </td>
                    <td>
                        <input class="sCelular" type="tel" name="celular" id="celular" maxlength="11" value="{{post.celular}}">
                    </td>
                </tr>    
            </table><br>    

            <!--Entrada de email-->
            <label class="campos" for="email">Email:</label><br>
            <input type="email" name="email" id="email" value="{{post.email}}">
            <p></p>

            <!--Entrada de endereço,rua-->
            <label class="campos" for="rua">Rua:</label><br>
            <input type="text" name="rua" id="rua" required value="{{post.rua}}">
            <p></p>

            <!--Tabela de entrada de bairro, cidade e estado-->
            <table>
                <tr>
                    <td>
                        <label class="campos" for="bairro">Bairro:</label>
                    </td>
                    <td>
                        <label class="campos" for="cidade">Cidade:</label>
                    </td>
                    <td>
                        <label class="campos" for="estado">Estado:</label>
                    </td>
                </tr>

                <tr>
                    <td>
                        <input class="sBairro" type="text" name="bairro" id="bairro"  required value="{{post.bairro}}">
                    </td>
                    <td >
                        <input class="sCidade" type="text" name="cidade" id="cidade"  required value="{{post.cidade}}">
                    </td>
                    <td>
                        <input class="sEstado" type="text" list="estado" name="estado" id="estado" required value="{{post.estado}}">
                    </td>
                </tr>
            </table><br>    

            <!--Entrada do complemento de endereço-->
            <label class="campos" for="complemento">Complemento:</label><br>
            <input type="text" name="complemento" id="complemento" value="{{post.complemento}}">
            <p></p>

            <!--Entrada do nível do aluno-->
            <label class="campos" for="nome">Nivelamento:</label><br>
            <table>
                <tr>
                    <td>
                        <input type="text" list="nivelamento" name="nivelamento" id="nivelamento" required value="{{post.nivelamento}}">
                    </td>
                    <datalist id="nivelamento">
                        <option value="Mouse e Teclado">mouseTeclado</option>
                        <option value="Iniciante">iniciante</option>
                        <option value="Internet Básico">internetBasico</option>
                        <option value="Escritório">escritorio</option>
                        <option value="Linux básico">linuxBasico</option>
                        <option value="Programação">programacao</option>
                    </datalist>
                </tr>
            </table>
            <p></p>

            <!--Botão de confirmação-->
            <button type="submit" class="save btn btn-default">Salvar</button>
        </form>
    </div>
</body>
{% endblock %}

HELP/aluno/templates/pesquisa.html
{% extends 'base.html' %}
{% block content %}
<body>
	<h2>Pesquisar Aluno:</h2>
	<div class="pesquisa-alunos"> <!-- caixa de pesquisa -->
		<form method="GET" action="">
			<input type="text" name="pesquisa" placeholder="Pesquisar por..." value = '{{ request.get.pesquisa }}'/>
			<button class="botaoPesquisar" type="submit">Pesquisar</button>
		</form>
	</div>

	<div class="lista-alunos"> <!-- imprimir alunos presente na lista alunos-->
		{% if query %}
		{% for aluno in alunos %}	
		<a href="{% url 'aluno:detalhes' pk=aluno.pk %}">{{ aluno.nome }}<br/></a>
		{% empty %}
		<p>{{query}} não foi encontrado(a) no sistema</p>
		{% endfor %}
		{% endif %}
	</div>
</body>
{% endblock %}